### ISSUE TITLE
Create dropdown UI for conversation options

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#175]
# Domain
app frontend

# Description
Develop a dropdown menu in the top bar of the conversation screen. The dropdown will include options for selecting different LLMs (OpenAI and Gemini) and saving the conversation, **focusing solely on the UI components without backend functionality integration.**

# Example
![Image](https://github.com/amosproj/amos2024ss06-health-ai-framework/assets/166435676/f0c3bf39-302c-4745-b895-86b22ae3bc5a)

# User Story
As a user, 
I need an organised way to access options related to my interactions with the agents
so that I can quickly and easily perform the respective actions.

# Acceptance Criteria
- [ ] A dropdown in the top of the conversation screen has been created.
- [ ] The dropdown has a dynamic title that shows the LLM name and version that is used for the current conversation.
- [ ] The dropdown has 3 options: 2 for selecting between the two LLMs and 1 for exporting the conversation / chat in txt as described in task #149 
  - [ ] GPT <Version>
  - [ ] Gemini <Version>
  - [ ] Save chat  
- [ ] The dropdown is extensible. It is done so that it can host more options in the near future.

# Definition of Done
- [ ] The feature has been fully implemented.
- [ ] The feature has been manually tested and works as expected without critical bugs.
- [ ] The feature code is documented with clear explanations of its functionality and usage.
- [ ] The feature code has been reviewed and approved by at least one team member.
- [ ] The feature branches have been merged into the main branch and closed.
- [ ] The feaure utility, function and usage have been documented in the respective project wiki on github.

**Comment by preetvadaliya** [comment]
This task will have following dependencies....

1. We need two custom hook top of the firebase, those will allow us to read and write chat related data from any context, because components will be in diff contexts.
2. Hooks:
   1. `useUpdateChat`
   2. `useGetChat`
3. both hook will takes the `id` of chat and returns the relevent logic.


### `useUpdateHook`

Params: `id`
Returns: `{updateChat(data), isUpdating, error}`

**Note:**
1. `updateChat` function shoud be able update single or multiple fields in firestore.
2. `isUpdating` help us to run spinner while making change in DB so meanwhile user can wait.
3. `error` if any error (I hope we always get it as null)


### `useGetChat`

Params: `id`
Returns: `{data, isLoading, error}`

**Note:**
1. `data` A firestore document that represent a single chat thread, can have following fields..
   1. chat title
   2. model name (last model name used by user)
   3. chat array
2. `isLoading` help us to run spinner while loading the chat.

From dropdown component it will update the data into firestore and same moment it will fetch the data from it in chat thread where we do query using LLM. (this type of realtime update is built in with firebase.)
